import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/providers/AuthProvider";
import { FirebaseAppCheckProvider } from "@/components/providers/FirebaseAppCheckProvider";
import { Toaster } from "@/components/ui/sonner";
import { PlayerProvider } from "@/components/player/PlayerProvider"; // Import PlayerProvider
import { MiniPlayer } from "@/components/player/MiniPlayer"; // Import MiniPlayer

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FirebaseAppCheckProvider>
          <AuthProvider>
            <PlayerProvider> {/* Wrap children with PlayerProvider */}
              {children}
              <MiniPlayer /> {/* Render MiniPlayer at the root */}
              <Toaster />
            </PlayerProvider>
          </AuthProvider>
        </FirebaseAppCheckProvider>
      </body>
    </html>
  );
}